title: 佐渡祭りカレンダー
description: 佐渡のどこでいつ祭りやイベントが行なわれるか？を誰でも簡単に調べて祭りに参加する人を増やすためのアプリです。
data_url: https://docs.google.com/spreadsheets/d/e/2PACX-1vRkVNzwuwa9FitLdMn_n7c53_Q4vSdKhAnbgs7QoMU_8Z1PmVdw6BuHak7HkjmutvPBZF_qVsjfS7F-/pub?gid=0&single=true&output=csv
form_url: null
logo_image_url: /logo.svg
background_image_url: /back.jpg
primary_color: "#00A0E6"
orderby: distance
# イベント情報表示用のCSV URL
event_data_url: https://docs.google.com/spreadsheets/d/e/2PACX-1vRkVNzwuwa9FitLdMn_n7c53_Q4vSdKhAnbgs7QoMU_8Z1PmVdw6BuHak7HkjmutvPBZF_qVsjfS7F-/pub?gid=0&single=true&output=csv

# 地図の初期表示設定
center:
  lat: 38.0
  lng: 138.37
zoom: 10